---
- hosts: database   
  roles:
    - mysql
  
- hosts: wordpress   
  roles:
    # - webserver
    - wordpress

    # - name: 'Configura apache para servir o wordpress'
    #   copy:
    #     src: 'files/000-default.conf'
    #     dest: '/etc/apache2/sites-available/000-default.conf'
    #   become: yes
    #   notify: "restart apache"