---
- hosts: database   
  handlers:
    - name: 'restart mysql'
      service:
        name: mysql
        state: restarted
      listen: "restart mysql"
      become: yes
  tasks:
    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        name: ['mysql-server-5.7','python3-mysqldb']
        state: latest
      become: yes
    - name: "Criar usuario no MySQL"
      mysql_user:
        login_user: root
        name: "{{wp_username}}"
        password: "{{wp_user_password}}"
        priv: "{{wp_db_name}}.*:ALL"
        state: present
        host: "{{item}}"
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - "{{wp_host_ip}}"
      become: yes
    - name: "Copiar arquivo mysqld.cnf"
      copy:
        src: /vagrant/configs/mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        owner: root
        group: root
        mode: 0644
      become: yes
      notify: "restart mysql"
    - name: 'Cria o banco do MySQL'
      mysql_db:
        name: "{{wp_db_name}}"
        state: present
      become: yes
- hosts: wordpress   
  handlers:    
    - name: 'restart apache'
      service:
        name: apache2
        state: restarted
      listen: "restart apache"
      become: yes
  tasks:
    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        name: ['php7.2','apache2','libapache2-mod-php7.2','php7.2-gd','php-ssh2','php7.2-mysql']
        state: latest
      become: yes
    - name : 'Download wordpress'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'
    - name: 'Descompactar o wordpress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: '/var/www/'
        remote_src: yes
      become: yes
    - name: 'Copiar arquivo'
      copy:
        src: "{{wp_installation_dir}}/wp-config-sample.php"
        dest: "{{wp_installation_dir}}/wp-config.php"
        remote_src: yes
      become: yes
    - name: 'Configurar o wp-config com as entradas do banco de dados'
      replace:
        path: "{{wp_installation_dir}}/wp-config.php"
        regexp: "{{ item.regex}}"
        replace: "{{ item.value }}"
        backup: yes
      with_items:
        - {regex: 'database_name_here', value: "{{wp_db_name}}"}
        - {regex: 'username_here', value: "{{wp_username}}"}
        - {regex: 'password_here', value: "{{wp_user_password}}"}
        - {regex: 'localhost', value: "{{wp_db_ip}}:3306"}
      become: yes

    - name: 'Configura Apache para servir Wordpress'
      template:
        src: 'templates/000-default.conf.j2'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify: "restart apache"

    # - name: 'Configura apache para servir o wordpress'
    #   copy:
    #     src: 'files/000-default.conf'
    #     dest: '/etc/apache2/sites-available/000-default.conf'
    #   become: yes
    #   notify: "restart apache"