---
- name : 'Download wordpress'
  get_url:
    url: 'https://wordpress.org/latest.tar.gz'
    dest: '/tmp/wordpress.tar.gz'
- name: 'Descompactar o wordpress'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www/'
    remote_src: yes
  become: yes
- name: 'Copiar arquivo'
  copy:
    src: "{{wp_installation_dir}}/wp-config-sample.php"
    dest: "{{wp_installation_dir}}/wp-config.php"
    remote_src: yes
  become: yes
- name: 'Configurar o wp-config com as entradas do banco de dados'
  replace:
    path: "{{wp_installation_dir}}/wp-config.php"
    regexp: "{{ item.regex}}"
    replace: "{{ item.value }}"
    backup: yes
  with_items:
    - {regex: 'database_name_here', value: "{{wp_db_name}}"}
    - {regex: 'username_here', value: "{{wp_username}}"}
    - {regex: 'password_here', value: "{{wp_user_password}}"}
    - {regex: 'localhost', value: "{{wp_db_ip}}:3306"}
  become: yes

- name: 'Configura Apache para servir Wordpress'
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify: "restart apache"