---
- name: 'Instala pacotes de dependencia do sistema operacional'
  apt:
    name: ['mysql-server-5.7','python3-mysqldb']
    state: latest
  become: yes

- name: "Criar usuario no MySQL"
  mysql_user:
    login_user: root
    name: "{{wp_username}}"
    password: "{{wp_user_password}}"
    priv: "{{wp_db_name}}.*:ALL"
    state: present
    host: "{{item}}"
  with_items:
    - 'localhost'
    - '127.0.0.1'
    - "{{wp_host_ip}}"
  become: yes

- name: "Copiar arquivo mysqld.cnf"
  copy:
    src: /vagrant/configs/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: "restart mysql"
  
- name: 'Cria o banco do MySQL'
  mysql_db:
    name: "{{wp_db_name}}"
    state: present
  become: yes